version: "3.8"
services:
  # Tên service, đặt là 'app' hay 'api' đều được
  api:
    # QUAN TRỌNG: Thay dòng dưới bằng tên repo GitHub của bạn
    # Ví dụ: ghcr.io/tuannguyen/booking-backend:latest
    image: ghcr.io/pad2806/convert_nextjs_to_nestjs_be:latest
    
    container_name: backend_prod
    restart: always
    ports:
      - "3001:3000" 
    environment:
      # Dokploy sẽ tự điền giá trị này từ tab Environment bạn đã cài
      - DATABASE_URL=postgresql://root:123456@bookingclinic-db-oeeoow:5432/booking_clinic_db
      - PORT=3000